name: maktab_lessor
description: A new Flutter project.

publish_to: 'none'


version: 1.0.13+15

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.1.4
  flutter_screenutil: ^5.9.1
  #  pin_code_fields: ^8.0.1
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  font_awesome_flutter: ^10.7.0
  dotted_border: ^2.1.0
  flutter_animate: ^4.5.0
  table_calendar: ^3.1.1
  lottie: ^3.1.2
  dropdown_button2: ^2.3.9
  video_player: ^2.8.6
  file_picker: ^8.0.3
  image_cropper: ^7.0.4
  flutter_typeahead: ^5.2.0
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  #  flutter_html: ^3.0.0-alpha.3
  equatable: ^2.0.5
  intl: ^0.19.0
  path_provider: ^2.1.3
  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  url_launcher: ^6.2.6
  dartz: ^0.10.1
  collection: ^1.18.0
  get_it: ^7.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3
  flutter_bloc: ^8.1.5

  syncfusion_flutter_datepicker: ^26.1.39
  jiffy: ^6.3.1
  pdf: ^3.10.8
  printing: ^5.12.0
  share_plus: ^9.0.0
  html_editor_enhanced: ^2.6.0
  flutter_widget_from_html: ^0.15.0
  pusher_channels_flutter: ^2.2.1
  flutter_local_notifications: ^17.1.2
  pinput: ^5.0.0
  app_links: ^6.1.1
  package_info_plus: ^8.0.0
  permission_handler: ^11.3.1
  flutter_quill: ^9.3.21
  smart_auth: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"
  change_app_package_name: ^1.2.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo3.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/TajawalBold.ttf
          weight: 700
        - asset: assets/fonts/TajawalMedium.ttf
          weight: 500
