name: maktab
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^12.1.1
  flutter_screenutil: ^5.9.0
  pin_code_fields: ^8.0.1
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  font_awesome_flutter: ^10.7.0
  dotted_border: ^2.1.0
  flutter_animate: ^4.5.0
  table_calendar: ^3.0.9
  lottie:
  dropdown_button2: ^2.3.8
  video_player: ^2.8.1
  file_picker: ^6.2.0
  image_cropper: ^5.0.1
  flutter_typeahead: ^5.2.0
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  flutter_html: ^3.0.0-alpha.3
  equatable: ^2.0.5
  intl: ^0.19.0
  path_provider: ^2.1.2
  google_maps_flutter: ^2.6.0
  geolocator: ^10.0.0
  url_launcher: ^6.2.6
  dartz: ^0.10.1
  collection: ^1.17.2
  get_it: ^7.6.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  flutter_bloc: ^8.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appicon.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/images/appicon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/appicon.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/images/appicon.png"

flutter:

  uses-material-design: true

  assets: 
    - assets/
    - assets/images/

  fonts: 
    - family: Tajawal
      fonts: 
        - asset: assets/fonts/TajawalBold.ttf
          weight: 700
        - asset: assets/fonts/TajawalMedium.ttf
          weight: 500
