name: maktab_lessor
description: "تطبيق مكتب أعمال هو تطبيق يوفر خدمة تأجير المكاتب في المملكة العربية السعودية من قبل المؤجرين ويسهم في استقطاب المستأجرين لهم. يوفر التطبيق أيضًا خدمات ومميزات مثل التعاقد الإلكتروني، إضافة العروض، كوبونات الخصم، وإدارة المكاتب ."

publish_to: 'none'


version: 1.0.21+23

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.6.0
  flutter_screenutil: ^5.9.3
  #  pin_code_fields: ^8.0.1
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.14
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.8.0
  dotted_border: ^2.1.0
  flutter_animate: ^4.5.0
  table_calendar: ^3.1.2
  lottie: ^3.1.3
  dropdown_button2: ^2.3.9
  video_player: ^2.9.2
  file_picker: ^8.1.4
  image_cropper: ^8.0.2
  flutter_typeahead: ^5.2.0
  smooth_page_indicator: ^1.2.0+3
  flutter_rating_bar: ^4.0.1
  #  flutter_html: ^3.0.0-alpha.3
  equatable: ^2.0.5
  intl: ^0.19.0
  path_provider: ^2.1.5
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  url_launcher: ^6.3.1
  dartz: ^0.10.1
  collection: ^1.18.0
  get_it: ^8.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  connectivity_plus: ^6.1.0
  flutter_bloc: ^8.1.6

  syncfusion_flutter_datepicker: ^27.1.58
  jiffy: ^6.3.1
  pdf: ^3.11.1
  printing: ^5.13.4
  share_plus: ^10.1.2
  html_editor_enhanced: ^2.6.0
  flutter_widget_from_html: ^0.15.2
  pusher_channels_flutter: ^2.5.0
  flutter_local_notifications: ^18.0.1
  pinput: ^5.0.0
#  app_links: ^6.4.0
  package_info_plus: ^8.1.1
  permission_handler: ^11.3.1
  flutter_quill: ^10.8.5
  smart_auth: ^2.0.0
  # because other packages depended on old versions
  # i force it by calling newer version of this packages
  audio_session: ^0.1.21 # -> flutter_widget_from_html: ^0.15.2
  just_audio: ^0.9.42 # -> flutter_widget_from_html: ^0.15.2
  video_player_android: ^2.7.16 # -> video_player: ^2.9.2
  flutter_inappwebview_android: ^1.1.3 # -> html_editor_enhanced: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  change_app_package_name: ^1.4.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo3.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/TajawalBold.ttf
          weight: 700
        - asset: assets/fonts/TajawalMedium.ttf
          weight: 500
